# Generated by Django 4.0 on 2023-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijistore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='items',
            name='discription',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='discription',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
