# Generated by Django 4.0 on 2023-02-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijistore', '0002_alter_items_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
