# Generated by Django 4.0 on 2023-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijistore', '0004_store_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Store'},
        ),
        migrations.AlterField(
            model_name='store',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
