# Generated by Django 4.0 on 2023-04-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jijiapp.store'),
        ),
    ]
