# Generated by Django 4.0 on 2023-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fas fa-utensils', 'Food'), ('fas fa-seedling', 'Agriculture'), ('fas fa-laptop', 'Computers'), ('fas fa-tv', 'Electronics'), ('fas fa-tshirt', 'Fashion'), ('fas fa-school', 'School'), ('fas fa-cut', 'Tailor'), ('fas fa-tools', 'Tools'), ('fas fa-mobile-alt', 'Phone'), ('fas fa-blender', 'Kitchen'), ('fas fa-car', 'Ride'), ('fas fa-car-side', 'Cars'), ('fas fa-building', 'Office'), ('fas fa-gem', 'Jewelry')], max_length=50),
        ),
    ]
