# Generated by Django 4.0 on 2023-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0002_alter_items_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('School', 'School'), ('Tailor', 'Tailor'), ('Tools', 'Tools'), ('Phone', 'Phone'), ('Kitechen', 'Kitechen'), ('Ride', 'Ride'), ('Cars', 'Cars'), ('Office', 'Office'), ('Food', 'Food')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(to='jijiapp.Category'),
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='jijiapp.Category'),
        ),
    ]
