# Generated by Django 4.0 on 2023-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0003_category_items_category_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(related_name='category', to='jijiapp.Category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(related_name='cat', to='jijiapp.Category'),
        ),
    ]
