# Generated by Django 4.0 on 2023-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='jijiapp.Category'),
        ),
    ]
