# Generated by Django 4.0 on 2023-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0004_alter_items_category_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Agri', 'Agriculture'), ('Comp', 'Computers'), ('Electric', 'Electronics'), ('FS', 'Fashion'), ('SCH', 'School'), ('T', 'Tailor'), ('Tools', 'Tools'), ('GSM', 'Phone'), ('Kch', 'Kitechen'), ('R', 'Ride'), ('C', 'Cars'), ('O', 'Office'), ('F', 'Food')], max_length=50),
        ),
    ]
