# Generated by Django 4.0 on 2023-04-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Computer', 'Computers'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('School', 'School'), ('Tailor', 'Tailor'), ('Tools', 'Tools'), ('Phone', 'Phone'), ('Kitchen', 'Kitechen'), ('Ride', 'Ride'), ('Car', 'Cars'), ('Office', 'Office'), ('Food', 'Food')], max_length=50),
        ),
    ]
