# Generated by Django 4.0 on 2023-05-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0007_alter_category_name_comment_items_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jijiapp.items'),
        ),
    ]
