# Generated by Django 4.0 on 2023-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0010_alter_useritemview_options_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
