# Generated by Django 4.0 on 2023-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0013_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
