# Generated by Django 4.0 on 2023-05-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0014_conversation_message_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message_count',
        ),
        migrations.CreateModel(
            name='ConversationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_count', to='jijiapp.conversation')),
            ],
        ),
    ]
