# Generated by Django 4.0 on 2023-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijiapp', '0015_remove_conversation_message_count_conversationcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationcount',
            name='message_count',
            field=models.IntegerField(default=1),
        ),
    ]
